# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec  6 17:01:49 2021
# ------------------------------------------------

package:
  name: fqdn
  version: 1.5.1
source:
  - folder: dist
    sha256: 105ed3677e767fb5ca086a0c1f4bb66ebc3c100be518f0e0d755d9eae164d89f
    url: https://pypi.io/packages/source/f/fqdn/fqdn-1.5.1.tar.gz
  - folder: src
    sha256: a2c026226f1a1eaace81362fda27b3df479693aefe19f160d6c4c3a032add498
    url: https://github.com/ypcrts/fqdn/archive/refs/tags/v1.5.1.tar.gz
build:
  noarch: python
  number: '0'
  script: cd dist && /home/conda/feedstock_root/build_artifacts/fqdn_1638810296540/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.10.0 h543edf9_3_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 59.4.0 py310hff52083_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - cached-property >=1.3.0
    - python >=2.7,<4
test:
  commands:
    - pip check
    - cd src/tests && pytest --cov=fqdn --cov-report=term-missing:skip-covered --no-cov-on-fail
      --cov-fail-under=95
  imports:
    - fqdn
  requires:
    - pip
    - pytest-cov
  source_files:
    - src/tests
about:
  home: https://github.com/ypcrts/fqdn
  license: MPL-2.0
  license_file: src/LICENSE
  summary: Validates fully-qualified domain names against RFC 1123, so that they are
    acceptable to modern bowsers
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
