[tool.black]
line-length = 80
target-version = ['py36']
exclude = '''
(
  /(
      \.eggs         # all directories in the root of the project
    | \.git
    | \.hg
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | \.svn
    | _build
    | buck-out
    | build
    | dist
    | astropy_helpers
    | model         # Temporary - to remove later
    | montecarlo    # Temporary
  )/
  | ah_bootstrap.py
  | ez_setup.py
  | setup.py
  | docs/conf.py
)
'''