$schema: http://json-schema.org/draft-04/schema#
type: object
additionalProperties: false
properties:
  tardis_config_version:
    type: string
    description: Version of the configuration file
  supernova:
    $ref: supernova.yml
  atom_data:
    type: string
    description: path or filename to the Atomic Data HDF5 file
  plasma:
    $ref: plasma.yml
  model:
    $ref: model.yml
  montecarlo:
    $ref: montecarlo.yml
  spectrum:
    $ref: spectrum.yml
required:
- tardis_config_version
- atom_data
- spectrum

