# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec 28 16:27:59 2023
# ------------------------------------------------

package:
  name: python-fastjsonschema
  version: 2.19.1
source:
  - folder: dist
    sha256: e3126a94bdc4623d3de4485f8d468a12f02a67921315ddc87836d6e456dc789d
    url: https://pypi.io/packages/source/f/fastjsonschema/fastjsonschema-2.19.1.tar.gz
  - folder: src
    sha256: 8c86c2eef8c52b8af584e920effd10bcb10e6417e0bbd560e16e6191bae2ec63
    url: https://github.com/horejsek/python-fastjsonschema/archive/v2.19.1.tar.gz
build:
  noarch: python
  number: '0'
  script: cd dist && /home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1703780968325/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.3
test:
  commands:
    - cd src && cd tests && pytest -vv --cov fastjsonschema -k "not (compile_to_code_ipv6_regex
      or compile_to_code_custom_format_with_refs)" --cov-report term-missing:skip-covered
      --no-cov-on-fail --cov-fail-under 84
  imports:
    - fastjsonschema
  requires:
    - pytest-benchmark
    - pytest-cov
  source_files:
    - src/tests
about:
  description: 'fastjsonschema implements validation of JSON documents by JSON schema.
    The

    library implements JSON schema drafts 04, 06 and 07. The main purpose is to

    have a really fast implementation.

    '
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs
  doc_url: https://horejsek.github.io/python-fastjsonschema
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231228.2.1
  recipe-maintainers:
    - bollwyvl
  remote_url: https://github.com/conda-forge/python-fastjsonschema-feedstock
  sha: 8d4dcce1232eb7a5c69d1af91e85fa7c5a503faf
