# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun  7 13:41:17 2024
# ------------------------------------------------

package:
  name: notebook
  version: 7.2.1
source:
  sha256: 4287b6da59740b32173d01d641f763d292f49c30e7a51b89c46ba8473126341e
  url: https://pypi.io/packages/source/n/notebook/notebook-7.2.1.tar.gz
build:
  entry_points:
    - jupyter-notebook = notebook.app:main
  noarch: python
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/notebook_1717767745914/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . --no-deps -vv --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - anyio 4.4.0 pyhd8ed1ab_0
    - argon2-cffi 23.1.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py312h98912ed_4
    - arrow 1.3.0 pyhd8ed1ab_0
    - asttokens 2.4.1 pyhd8ed1ab_0
    - async-lru 2.0.4 pyhd8ed1ab_0
    - attrs 23.2.0 pyh71513ae_0
    - babel 2.14.0 pyhd8ed1ab_0
    - beautifulsoup4 4.12.3 pyha770c72_0
    - bleach 6.1.0 pyhd8ed1ab_0
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - cached-property 1.5.2 hd8ed1ab_1
    - cached_property 1.5.2 pyha770c72_1
    - certifi 2024.2.2 pyhd8ed1ab_0
    - cffi 1.16.0 py312hf06ca03_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - comm 0.2.2 pyhd8ed1ab_0
    - debugpy 1.8.1 py312h30efb56_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - editables 0.5 pyhd8ed1ab_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - exceptiongroup 1.2.0 pyhd8ed1ab_2
    - executing 2.0.1 pyhd8ed1ab_0
    - fqdn 1.5.1 pyhd8ed1ab_0
    - h11 0.14.0 pyhd8ed1ab_0
    - h2 4.1.0 pyhd8ed1ab_0
    - hatch-jupyter-builder 0.9.1 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - hpack 4.0.0 pyh9f0ad1d_0
    - httpcore 1.0.5 pyhd8ed1ab_0
    - httpx 0.27.0 pyhd8ed1ab_0
    - hyperframe 6.0.1 pyhd8ed1ab_0
    - idna 3.7 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - importlib_metadata 7.1.0 hd8ed1ab_0
    - importlib_resources 6.4.0 pyhd8ed1ab_0
    - ipykernel 6.29.4 pyh3099207_0
    - ipython 8.25.0 pyh707e725_0
    - isoduration 20.11.0 pyhd8ed1ab_0
    - jedi 0.19.1 pyhd8ed1ab_0
    - jinja2 3.1.4 pyhd8ed1ab_0
    - json5 0.9.25 pyhd8ed1ab_0
    - jsonpointer 2.4 py312h7900ff3_3
    - jsonschema 4.22.0 pyhd8ed1ab_0
    - jsonschema-specifications 2023.12.1 pyhd8ed1ab_0
    - jsonschema-with-format-nongpl 4.22.0 pyhd8ed1ab_0
    - jupyter-lsp 2.2.5 pyhd8ed1ab_0
    - jupyter_client 8.6.2 pyhd8ed1ab_0
    - jupyter_core 5.7.2 py312h7900ff3_0
    - jupyter_events 0.10.0 pyhd8ed1ab_0
    - jupyter_server 2.14.1 pyhd8ed1ab_0
    - jupyter_server_terminals 0.5.3 pyhd8ed1ab_0
    - jupyterlab 4.2.1 pyhd8ed1ab_0
    - jupyterlab_pygments 0.3.0 pyhd8ed1ab_1
    - jupyterlab_server 2.27.2 pyhd8ed1ab_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 hf3520f5_2
    - libedit 3.1.20191231 he28a2e2_2
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - markupsafe 2.1.5 py312h98912ed_0
    - matplotlib-inline 0.1.7 pyhd8ed1ab_0
    - mistune 3.0.2 pyhd8ed1ab_0
    - nbclient 0.10.0 pyhd8ed1ab_0
    - nbconvert-core 7.16.4 pyhd8ed1ab_0
    - nbformat 5.10.4 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - nest-asyncio 1.6.0 pyhd8ed1ab_0
    - notebook-shim 0.2.4 pyhd8ed1ab_0
    - openssl 3.3.1 h4ab18f5_0
    - overrides 7.7.0 pyhd8ed1ab_0
    - packaging 24.0 pyhd8ed1ab_0
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - parso 0.8.4 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pexpect 4.9.0 pyhd8ed1ab_0
    - pickleshare 0.7.5 py_1003
    - pip 24.0 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_1
    - platformdirs 4.2.2 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - prometheus_client 0.20.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.46 pyha770c72_0
    - psutil 5.9.8 py312h98912ed_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - pycparser 2.22 pyhd8ed1ab_0
    - pygments 2.18.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.3 hab00c5b_0_cpython
    - python-dateutil 2.9.0 pyhd8ed1ab_0
    - python-fastjsonschema 2.19.1 pyhd8ed1ab_0
    - python-json-logger 2.0.7 pyhd8ed1ab_0
    - python_abi 3.12 4_cp312
    - pytz 2024.1 pyhd8ed1ab_0
    - pyyaml 6.0.1 py312h98912ed_1
    - pyzmq 26.0.3 py312h8fd38d8_0
    - readline 8.2 h8228510_1
    - referencing 0.35.1 pyhd8ed1ab_0
    - requests 2.32.3 pyhd8ed1ab_0
    - rfc3339-validator 0.1.4 pyhd8ed1ab_0
    - rfc3986-validator 0.1.1 pyh9f0ad1d_0
    - rpds-py 0.18.1 py312h4413252_0
    - send2trash 1.8.3 pyh0d859eb_0
    - setuptools 70.0.0 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - sniffio 1.3.1 pyhd8ed1ab_0
    - soupsieve 2.5 pyhd8ed1ab_1
    - stack_data 0.6.2 pyhd8ed1ab_0
    - terminado 0.18.1 pyh0d859eb_0
    - tinycss2 1.3.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.4.1 py312h9a8786e_0
    - traitlets 5.14.3 pyhd8ed1ab_0
    - trove-classifiers 2024.5.22 pyhd8ed1ab_0
    - types-python-dateutil 2.9.0.20240316 pyhd8ed1ab_0
    - typing-extensions 4.12.1 hd8ed1ab_0
    - typing_extensions 4.12.1 pyha770c72_0
    - typing_utils 0.1.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - uri-template 1.3.0 pyhd8ed1ab_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wcwidth 0.2.13 pyhd8ed1ab_0
    - webcolors 24.6.0 pyhd8ed1ab_0
    - webencodings 0.5.1 pyhd8ed1ab_2
    - websocket-client 1.8.0 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - yaml 0.2.5 h7f98852_2
    - zeromq 4.3.5 h75354e8_4
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - jupyter_server >=2.4.0,<3
    - jupyterlab >=4.2.0,<4.3
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2,<0.3
    - python >=3.8
    - tornado >=6.2.0
test:
  commands:
    - pip check
    - jupyter notebook -h
    - jupyter-notebook -h
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyter-notebook/lab-extension.*OK" labextensions
  imports:
    - notebook
  requires:
    - pip
about:
  doc_source_url: https://github.com/jupyter/notebook/tree/v7.2.1/docs
  doc_url: https://jupyter-notebook.readthedocs.io
  home: https://github.com/jupyter/notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - notebook/labextension/static/third-party-licenses.json
    - notebook/static/third-party-licenses.json
  summary: A web-based notebook environment for interactive computing
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240607.4.1
  recipe-maintainers:
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - davidbrochart
    - gnestor
    - jakirkham
    - jtpio
    - lresende
    - minrk
    - pelson
    - takluyver
  remote_url: https://github.com/conda-forge/notebook-feedstock
  sha: ec4ae054d04c8ae36185e41f91475d25d635bdc7
