model:
    structure:
        type: specific


        velocity:
            start : 1.1e4 km/s
            stop : 20000 km/s
            num: 20
            
            
        density:
            type : exponential
            time_0: 2. day
            rho_0: 6.e-10 g/cm^3
            v_0: 3000.  km/s
