
.. azure stuff
.. _azure DevOps: http://azure.microsoft.com/en-us/services/devops/?nav=mi
.. _azure documentation section on triggers: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
.. _azure variables: http://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

.. general stuff
.. _continuous integration: https://en.wikipedia.org/wiki/Continuous_integration

.. |emdash| unicode:: U+02014

.. vim: ft=rstS

