
.. matterbridge stuff
.. _OpenSupernova.org: http://opensupernova.org
.. _private GitHub repository: https://github.com/tardis-sn/tardis-matterbridge
.. _Upstart script: https://www.digitalocean.com/community/tutorials/the-upstart-event-system-what-it-is-and-how-to-use-it
.. _Systemd service: https://freedesktop.org/software/systemd/man/systemd.service.html
.. _steps for Slack in the Matterbridge wiki: https://github.com/42wim/matterbridge/wiki/Slack-bot-setup
.. _steps for Mattermost in the Matterbridge wiki: https://github.com/42wim/matterbridge/wiki/Section-Mattermost-%28basic%29
.. _this comment: https://github.com/42wim/matterbridge/issues/964#issuecomment-612721850
.. _this link: https://developer.gitter.im/docs/authentication
.. _releases section: https://github.com/42wim/matterbridge/releases/latest
