#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 54
#define PANGO_VERSION_MICRO 0

#define PANGO_VERSION_STRING "1.54.0"

#endif /* PANGO_FEATURES_H */
