#
# Configuration file for using the xslt library
#
XSLT_LIBDIR="-L/home/conda/feedstock_root/build_artifacts/libxslt_1701628586713/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib"
XSLT_LIBS="-lxslt -L/home/conda/feedstock_root/build_artifacts/libxslt_1701628586713/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -lxml2 "
XSLT_PRIVATE_LIBS="-lm"
XSLT_INCLUDEDIR="-I/home/conda/feedstock_root/build_artifacts/libxslt_1701628586713/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include"
MODULE_VERSION="xslt-1.1.39"
