# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Nov  2 16:23:14 2022
# ------------------------------------------------

package:
  name: qgrid
  version: 1.3.1
source:
  sha256: fe8af5b50833084dc0b6a265cd1ac7b837c03c0f8521150163560dce778d711c
  url: https://pypi.io/packages/source/q/qgrid/qgrid-1.3.1.tar.gz
build:
  noarch: python
  number: '4'
  script: /home/conda/feedstock_root/build_artifacts/qgrid_1667406267807/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_4
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - anyio 3.6.2 pyhd8ed1ab_0
    - argon2-cffi 21.3.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py311hd4cff14_3
    - asttokens 2.1.0 pyhd8ed1ab_0
    - attrs 22.1.0 pyh71513ae_1
    - backcall 0.2.0 pyh9f0ad1d_0
    - backports 1.0 py_2
    - backports.functools_lru_cache 1.6.4 pyhd8ed1ab_0
    - beautifulsoup4 4.11.1 pyha770c72_0
    - bleach 5.0.1 pyhd8ed1ab_0
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - cffi 1.15.1 py311h409f033_2
    - debugpy 1.6.3 py311ha362b79_1
    - decorator 5.1.1 pyhd8ed1ab_0
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - executing 1.2.0 pyhd8ed1ab_0
    - flit-core 3.7.1 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - importlib-metadata 5.0.0 pyha770c72_1
    - importlib_resources 5.10.0 pyhd8ed1ab_0
    - ipykernel 6.17.0 pyh210e3f2_0
    - ipython 8.6.0 pyh41d4057_1
    - ipython_genutils 0.2.0 py_1
    - jedi 0.18.1 pyhd8ed1ab_2
    - jinja2 3.1.2 pyhd8ed1ab_1
    - jsonschema 4.17.0 pyhd8ed1ab_0
    - jupyter_client 7.4.4 pyhd8ed1ab_0
    - jupyter_core 4.11.1 py311h38be061_1
    - jupyter_server 1.21.0 pyhd8ed1ab_0
    - jupyterlab_pygments 0.2.2 pyhd8ed1ab_0
    - ld_impl_linux-64 2.39 hc81fddc_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.39.4 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - markupsafe 2.1.1 py311hd4cff14_2
    - matplotlib-inline 0.1.6 pyhd8ed1ab_0
    - mistune 2.0.4 pyhd8ed1ab_0
    - nbclassic 0.4.5 pyhd8ed1ab_0
    - nbclient 0.7.0 pyhd8ed1ab_0
    - nbconvert 7.2.3 pyhd8ed1ab_0
    - nbconvert-core 7.2.3 pyhd8ed1ab_0
    - nbconvert-pandoc 7.2.3 pyhd8ed1ab_0
    - nbformat 5.7.0 pyhd8ed1ab_0
    - ncurses 6.3 h27087fc_1
    - nest-asyncio 1.5.6 pyhd8ed1ab_0
    - notebook 6.5.1 pyha770c72_0
    - notebook-shim 0.2.0 pyhd8ed1ab_0
    - openssl 3.0.7 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pandoc 2.19.2 h32600fe_1
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - parso 0.8.3 pyhd8ed1ab_0
    - pexpect 4.8.0 pyh1a96a4e_2
    - pickleshare 0.7.5 py_1003
    - pip 22.3 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_0
    - prometheus_client 0.15.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.31 pyha770c72_0
    - psutil 5.9.3 py311hd4cff14_1
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pygments 2.13.0 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - pyrsistent 0.19.1 py311hd4cff14_0
    - python 3.11.0 ha86cf86_0_cpython
    - python-dateutil 2.8.2 pyhd8ed1ab_0
    - python-fastjsonschema 2.16.2 pyhd8ed1ab_0
    - python_abi 3.11 2_cp311
    - pyzmq 24.0.1 py311ha4b6469_1
    - readline 8.1.2 h0f457ee_0
    - send2trash 1.8.0 pyhd8ed1ab_0
    - setuptools 65.5.0 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - sniffio 1.3.0 pyhd8ed1ab_0
    - soupsieve 2.3.2.post1 pyhd8ed1ab_0
    - stack_data 0.6.0 pyhd8ed1ab_0
    - terminado 0.17.0 pyh41d4057_0
    - tinycss2 1.2.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tornado 6.2 py311hd4cff14_1
    - traitlets 5.5.0 pyhd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022f h191b570_0
    - wcwidth 0.2.5 pyh9f0ad1d_2
    - webencodings 0.5.1 py_1
    - websocket-client 1.4.1 pyhd8ed1ab_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zeromq 4.3.4 h9c3ff4c_1
    - zipp 3.10.0 pyhd8ed1ab_0
  run:
    - ipywidgets >=7.0.0,<8
    - nbclassic >=0.4.4
    - notebook >=4.0.0
    - pandas >=0.17.0
    - python >=2.7
test:
  imports:
    - qgrid
    - qgrid.tests
about:
  description: 'Qgrid is a Jupyter notebook widget which uses SlickGrid to render
    pandas DataFrames.

    This allows you to explore your DataFrames with intuitive scrolling, sorting,
    and

    filtering controls, as well as edit your DataFrames by double clicking cells.

    '
  dev_url: https://github.com/quantopian/qgrid
  doc_source_url: https://github.com/quantopian/qgrid/blob/master/docs/index.rst
  doc_url: http://qgrid.readthedocs.org/en/latest/
  home: https://github.com/quantopian/qgrid
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pandas DataFrame viewer for Jupyter Notebook
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - TimShawver
    - alen12345
    - xhochy
