#!/bin/sh
'''exec' /home/conda/feedstock_root/build_artifacts/numpydoc_1717502870243/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from numpydoc.hooks.validate_docstrings import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
