# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Mar  1 13:28:10 2024
# ------------------------------------------------

package:
  name: python-dateutil
  version: 2.9.0
source:
  sha256: 78e73e19c63f5b20ffa567001531680d939dc042bf7850431877645523c66709
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.9.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.10.0 hd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
    - six >=1.5
test:
  commands:
    - pip check
  imports:
    - dateutil
    - dateutil.parser
  requires:
    - pip
about:
  description: 'The dateutil module provides powerful extensions to the standard datetime

    module, available in Python.

    '
  dev_url: https://github.com/dateutil/dateutil/
  doc_url: https://dateutil.readthedocs.org/en/latest/
  home: https://dateutil.readthedocs.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240301.3.1
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pganssle
  remote_url: https://github.com/conda-forge/python-dateutil-feedstock
  sha: 74d23dd0ce9b3ed58f81a433a3ca85f1ecfcf4e5
