# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: setuptools-scm
  version: 8.1.0
source:
  sha256: 42dea1b65771cba93b7a515d65a65d8246e560768a66b9106a592c8e7f26c8a7
  url: https://pypi.io/packages/source/s/setuptools-scm/setuptools_scm-8.1.0.tar.gz
build:
  noarch: python
  number: 0
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - packaging >=20.0
    - python >=3.8
    - setuptools >=45
    - tomli >=1.0.0
    - typing-extensions
test:
  commands:
    - pip check
  imports:
    - setuptools_scm
  requires:
    - pip
about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  license_file: LICENSE
  summary: The blessed package to manage your versions by scm tags
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240507.5.1
  recipe-maintainers:
    - astaric
    - kwilcox
    - ocefpaf
  remote_url: https://github.com/conda-forge/setuptools_scm-feedstock
  sha: 0ee72c777c876ca9eb7e4edb0940418cda0e7e56
