#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 52
#define PANGO_VERSION_MICRO 2

#define PANGO_VERSION_STRING "1.52.2"

#endif /* PANGO_FEATURES_H */
