# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: jupyter-lsp
  version: 2.2.5
source:
  - folder: jupyterlab-lsp
    sha256: aeac84093ada6d20ef57ae0e97811cc5796a0cab7237b32f8eddf993c0bb0356
    url: https://pypi.io/packages/source/j/jupyterlab-lsp/jupyterlab-lsp-5.1.0.tar.gz
  - folder: jupyter-lsp
    sha256: 793147a05ad446f809fd53ef1cd19a9f5256fd0a2d6b7ce943a982cb4f545001
    url: https://pypi.io/packages/source/j/jupyter-lsp/jupyter-lsp-2.2.5.tar.gz
build:
  noarch: python
  number: 0
  script: cd jupyter-lsp && /home/conda/feedstock_root/build_artifacts/jupyter-lsp-meta_1712707420468/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - importlib-metadata >=4.8.3
    - jupyter_server >=1.1.2
    - python >=3.8
test:
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - grep -iE "jupyter_lsp.*OK" server_extensions
  requires:
    - pip
about:
  doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs
  doc_url: https://jupyterlab-lsp.readthedocs.io
  home: https://github.com/jupyter-lsp/jupyterlab-lsp
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupyter-lsp/LICENSE
  summary: Multi-Language Server WebSocket proxy for Jupyter Server
extra:
  copy_test_source_files: true
  feedstock-name: jupyter-lsp
  final: true
  flow_run_id: azure_20240409.3.1
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - krassowski
  remote_url: https://github.com/conda-forge/jupyter-lsp-feedstock
  sha: 644ca77f9664cfbace49800da3f69cb3c82dead4
