# Autogenerated by Astropy-affiliated package tardis's setup.py on 2013-06-12 16:25:56.989362

from astropy.version_helpers import update_git_devstr, get_git_devstr

_last_generated_version = '0.9.dev368'

version = update_git_devstr(_last_generated_version)
githash = get_git_devstr(sha=True, show_warning=False)

major = 0
minor = 9
bugfix = 0

release = False
debug = False

try:
    from astropy.utils._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from astropy.cython_version import cython_version
except ImportError:
    cython_version = "unknown"
