name: "Setup environment"
description: "Sets up environment for tardis and caches it"

inputs:
  os-label:
    description: "os label for lock file, default linux"
    required: true
    default: "linux"

runs:
  using: "composite"
  steps:
      - name: Setup environment
        uses: tardis-sn/tardis-actions/setup-env@main
        with:
          os-label: ${{ inputs.os-label }}
