# For more information on how to use this pipeline please refer to:
# https://tardis-sn.github.io/tardis/contributing/development/continuous_integration.html

# IMPORTANT: Only contributors with `Write` permission can trigger the build
#            by commenting `/AzurePipelines run <pipeline-name>` on the pull
#            request.
#
#            This feature can be disabled only through the Azure Pipelines
#            dashboard.

trigger:
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
  pr.number: '$(System.PullRequest.PullRequestNumber)'
  commit.sha: '$(Build.SourceVersion)'
  results.url: 'http://opensupernova.org/~azuredevops/files/refdata-results'
  #ref1.hash: ''
  #ref2.hash: ''

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'report'
    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          refdataRepo: 'azure'  # use 'github' when comparing between custom ref hashes
          useMamba: false

      - bash: |
          source activate tardis
          $(package.manager) install bokeh=2.2 --channel conda-forge --no-update-deps --yes
        displayName: 'Install Bokeh'

      - bash: |
          cd $(refdata.dir)
          git remote add upstream $(git remote get-url origin)
          git fetch upstream
        displayName: 'Set upstream remote'

      - ${{ if or(startsWith(variables['ref1.hash'], 'upstream/pr'), startsWith(variables['ref2.hash'], 'upstream/pr')) }}:
        - bash: |
            cd $(refdata.dir)
            git fetch upstream "+refs/pull/*/head:refs/remotes/upstream/pr/*"
          displayName: 'Fetch pull requests'

      - bash: |
          cd $(tardis.dir)
          source activate tardis
          pytest tardis --tardis-refdata=$(refdata.dir) --generate-reference
        displayName: 'Generate reference data'
        condition: or(eq(variables['ref1.hash'], ''), eq(variables['ref2.hash'], ''))

      - bash: |
          cd $(refdata.dir)/notebooks
          source activate tardis
          jupyter nbconvert ref_data_compare.ipynb --to html --execute --ExecutePreprocessor.timeout=6000
        displayName: 'Render notebook'

      - bash: |
          cd $(refdata.dir)/notebooks
          source activate tardis
          jupyter nbconvert ref_data_compare.ipynb --to html --execute --allow-errors --ExecutePreprocessor.timeout=6000
        displayName: 'Render notebook (allow errors)'
        condition: failed()

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(refdata.dir)/notebooks/ref_data_compare.html'
          artifactName: 'report'
        displayName: 'Upload artifact'
        condition: succeededOrFailed()

      - task: InstallSSHKey@0
        inputs:
         knownHostsEntry: $(opensupernova_host)
         sshPublicKey: $(opensupernova_pubkey)
         sshKeySecureFile: openSupernovaKey

      - ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
        - bash: echo "##vso[task.setvariable variable=subfolder]releases"
          displayName: "Set subfolder name"

      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        - bash: echo "##vso[task.setvariable variable=subfolder]$(pr.number)"
          displayName: "Set subfolder name"

      - ${{ if eq(variables['Build.Reason'], 'Manual') }}:
        - bash: echo "##vso[task.setvariable variable=subfolder]manual"
          displayName: "Set subfolder name"

      - bash: |
          ssh azuredevops@opensupernova.org "mkdir -p /home/azuredevops/public_html/files/refdata-results/$(subfolder)"
          scp $(refdata.dir)/notebooks/ref_data_compare.html azuredevops@opensupernova.org:/home/azuredevops/public_html/files/refdata-results/$(subfolder)/$(commit.sha).html
        displayName: 'Copy files to server'
        condition: succeededOrFailed()

      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        - task: GitHubComment@0
          inputs:
            gitHubConnection: 'tardis-sn'
            repositoryName: 'tardis-sn/tardis'
            id: $(pr.number)
            comment: '**Build succeeded** $(commit.sha) <br><br> [Click here]($(results.url)/$(pr.number)/$(commit.sha).html) to see results.'
          displayName: 'Post results (success)'

        - task: GitHubComment@0
          inputs:
            gitHubConnection: 'tardis-sn'
            repositoryName: 'tardis-sn/tardis'
            id: $(pr.number)
            comment: '**Build failed** $(commit.sha) <br><br> [Click here]($(results.url)/$(pr.number)/$(commit.sha).html) to see results.'
          displayName: 'Post results (failed)'
          condition: failed()
