# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

trigger: none
pr: none

schedules:
  - cron: '0 0 * * 0'
    displayName: 'Weekly release'
    branches:
      include:
        - master
    always: false

variables:
  system.debug: false

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: release
    displayName: 'TARDIS release'

    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          refdataRepo: 'azure'
          useMamba: true

      # Test before relase, we do not want to release broken software!
      - bash: |
          cd $(tardis.dir)
          source activate tardis
          pytest tardis --tardis-refdata=$(refdata.dir)
        displayName: 'Run tests'

      - bash: |
          cd $(tardis.dir)
          source activate tardis
          echo $(python .ci-helpers/get_current_version.py)
        displayName: 'Check latest tag'

      - bash: |
          cd $(tardis.dir)
          source activate tardis
          echo "##vso[task.setvariable variable=newtag]$(python .ci-helpers/get_next_version.py)"
        displayName: 'Get new tag'

      - bash: echo $(newtag)
        displayName: 'Check new tag'

      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'tardis-bot'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'userSpecifiedTag'
          tag: 'release-$(newtag)'
          title: 'TARDIS v$(newtag)'
          releaseNotesSource: 'inline'
          releaseNotes: 'This release has been made automatically through our continous delivery pipeline. For a complete list of changes see [CHANGELOG.md](https://github.com/tardis-sn/tardis/blob/master/CHANGELOG.md).'
          addChangeLog: false
        displayName: 'Create GitHub Release'
