# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

# IMPORTANT: Only contributors with `Write` permission can trigger the build
#            by commenting `/AzurePipelines run <pipeline-name>` on the pull
#            request.
#
#            This feature can be disabled only through the Azure Pipelines
#            dashboard.

trigger: none

pr:
  branches:
    include:
    - master

variables:
  system.debug: false
  commit.sha: '$(Build.SourceVersion)'
  pr.number: '$(System.PullRequest.PullRequestNumber)'
  build.id: '$(Build.BuildId)'
  job.id: '$(System.JobId)'
  log.url: 'https://dev.azure.com/tardis-sn/TARDIS/_build/results?buildId=$(build.id)&view=logs&jobId=$(job.id)'
  github.token: '$(bot_token)'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'push'
    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          refdataRepo: 'github'
          useMamba: true

      - bash: |
          cd $(tardis.dir)
          git checkout -b pr-$(pr.number)

          source activate tardis
          pytest tardis --tardis-refdata=$(refdata.dir) --generate-reference
        displayName: 'Generate reference data on a new branch'

      - bash: |
          cd $(refdata.dir)
          git add unit_test_data.h5 montecarlo_1e5_compare_data.h5
          git config --local user.email "tardis.sn.bot@gmail.com"
          git config --local user.name "tardis-bot"
          git commit -m "Automated Update (PR $(pr.number))"
        displayName: 'Commit new reference data'

      - bash: |
          gh pr create --title "Automated Update (PR $(pr.number))" --body "Pull request generated by TARDIS [pull request #$(pr.number)](https://github.com/tardis-sn/tardis/pull/$(pr.number))"
        displayName: 'Propose changes via pull request'
