# For more information on how to use this pipeline please refer to:
# https://tardis-sn.github.io/tardis/contributing/development/continuous_integration.html

# IMPORTANT: Only contributors with `Write` permission can trigger the build
#            by commenting `/AzurePipelines run <pipeline-name>` on the pull
#            request.
#
#            This feature can be disabled only through the Azure Pipelines
#            dashboard.

trigger: none

pr:
  branches:
    include:
    - master

variables:
  system.debug: false
  pr.number: '$(System.PullRequest.PullRequestNumber)'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'pull_request'
    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          refdataRepo: 'github'
          useMamba: false

      - bash: |
          cd $(refdata.dir)
          git remote add fork https://$(bot_token)@github.com/tardis-bot/tardis-refdata
          git checkout -B pr-$(pr.number)
        displayName: 'Set up new branch'

      - bash: |
          cd $(tardis.dir)
          source activate tardis
          pytest tardis --tardis-refdata=$(refdata.dir) --generate-reference
        displayName: 'Generate reference data on a new branch'

      - bash: |
          cd $(refdata.dir)
          git add -A
          git config --local user.email "tardis.sn.bot@gmail.com"
          git config --local user.name "tardis-bot"
          git commit -m "Automated Update (PR $(pr.number))"
          git push fork pr-$(pr.number) -f
        displayName: 'Commit new reference data'

      - bash: |
          cd $(refdata.dir)

          # Check if pull request already exists
          STATE=$(gh pr list --repo tardis-sn/tardis-refdata -H pr-$(pr.number) --json state | jq -r .[].state)
          if [[ ! -z "$STATE" ]]; then

            echo "$(bot_token)" | gh auth login --with-token
            gh pr create --repo tardis-sn/tardis-refdata --head tardis-bot:pr-$(pr.number) --title "Automated Update (PR $(pr.number))" --body "_Pull request automatically generated by [#$(pr.number)](https://github.com/tardis-sn/tardis/pull/$(pr.number))_"

          else
            exit 0

          fi
        displayName: 'Propose changes via pull request'
