# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

# IMPORTANT: Only contributors with `Write` permission can trigger the build
#            by commenting `/AzurePipelines run <pipeline-name>` on the pull
#            request.
#
#            This feature can be disabled only through the Azure Pipelines
#            dashboard.

trigger: none

pr:
  branches:
    include:
    - master

variables:
  system.debug: false
  pr.number: '$(System.PullRequest.PullRequestNumber)'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'pull_request'
    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          refdataRepo: 'github'
          useMamba: true

      - bash: |
          cd $(tardis.dir)
          git checkout -b pr-$(pr.number)

          source activate tardis
          pytest tardis --tardis-refdata=$(refdata.dir) --generate-reference
        displayName: 'Generate reference data on a new branch'

      - bash: |
          cd $(refdata.dir)
          git add -A
          git config --local user.email "tardis.sn.bot@gmail.com"
          git config --local user.name "tardis-bot"
          git commit -m "Automated Update (PR $(pr.number))"
        displayName: 'Commit new reference data'

      - bash: |
          gh auth login --with-token $(bot_token)
          gh pr create --title "Automated Update (PR $(pr.number))" --body "Pull request automatically generated by TARDIS [pull request #$(pr.number)](https://github.com/tardis-sn/tardis/pull/$(pr.number))"
        displayName: 'Propose changes via pull request'
