name: benchmarks

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

    types:
      - opened
      - reopened
      - synchronize
      - labeled # benchmarks label required
      - ready_for_review
  workflow_dispatch:

env:
  DEPLOY_BRANCH: main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-cache:
    uses: ./.github/workflows/lfs-cache.yml
    with:
      atom-data-sparse: false
      regression-data-repo: tardis-sn/tardis-regression-data

  build:
    if: github.repository_owner == 'tardis-sn' &&
      (github.event_name == 'push' ||
      (!github.event.pull_request.draft) ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
    runs-on: ubuntu-latest
    needs: [test-cache]
    steps:
      - uses: actions/checkout@v6
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: Checkout PR and master branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
        if: github.event_name == 'pull_request'

      - name: Fetch master branch
        run: git fetch origin master:master
        if: github.event_name == 'pull_request'

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
        with:
          atom-data-sparse: true

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: benchmark
          init-shell: >-
            bash
          create-args: >-
            python
            asv=0.6.4
            mamba
            libmambapy<2.0
            conda-build
            conda=24.11.0

      - name: Accept all asv questions
        run: asv machine --yes

      - name: Download environment file for benchmarks
        run: wget -q https://raw.githubusercontent.com/tardis-sn/tardisbase/refs/heads/master/env-benchmark-linux.yml

      - name: Run benchmarks for last 4 commits if not PR
        if: github.event_name != 'pull_request'
        run: |
          git log -n 4  --pretty=format:"%H" >> tag_commits.txt
          asv run -a rounds=1 HASHFILE:tag_commits.txt | tee asv-output.log
          if grep -q failed asv-output.log; then 
            echo "Some benchmarks have failed!"
            exit 1
          fi

      - name: Generate Graphs and HTML
        if: github.event_name != 'pull_request'
        run: asv publish

      - name: Delete env files
        if: github.event_name != 'pull_request'
        run: rm -r .asv/env

      - name: Deploy asv page
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.BOT_TOKEN }}
          publish_branch: ${{ env.DEPLOY_BRANCH }}
          publish_dir: .asv/html
          keep_files: true
          external_repository: tardis-sn/tardis-benchmarks
          user_name: "TARDIS Bot"
          user_email: "tardis.sn.bot@gmail.com"
          full_commit_message: |
            deploy: master - ${{ github.event.head_commit.message }}

            This is an automated benchmark deploy.
            Triggered by: push to master
            Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Run benchmarks for base and head commits of PR
        if: github.event_name == 'pull_request'
        run: |
          echo $(git rev-parse HEAD) > commit_hashes.txt
          echo $(git rev-parse master) >> commit_hashes.txt
          asv run -a rounds=1 HASHFILE:commit_hashes.txt | tee asv-output-PR.log  
            if grep -q failed asv-output-PR.log; then 
              echo "Some benchmarks have failed!"
              exit 1
            fi

      - name: Compare Master and PR head
        run: asv compare origin/master HEAD --factor 1.1 --split --sort ratio | tee asv-compare-output.log

      - name: Compare Master and PR head but only show changed results
        run: asv compare origin/master HEAD --only-changed --factor 1.1 --split --sort ratio | tee asv-compare-changed-output.log

      - name: Check for significantly changed benchmarks
        id: significant_benchmarks
        if: github.event_name == 'pull_request'
        run: |
          if grep -Eq '^\| [-+!] +\|' asv-compare-changed-output.log; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Significantly changed benchmarks found."
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No significantly changed benchmarks found."
          fi

      - name: Benchmarks compare output
        id: asv_pr_vs_master
        uses: juliangruber/read-file-action@v1.1.8
        with:
          path: asv-compare-output.log

      - name: Benchmarks compare only changed output
        id: asv_pr_vs_master_changed
        uses: juliangruber/read-file-action@v1.1.8
        with:
          path: asv-compare-changed-output.log

      - name: Generate Graphs and HTML of PR
        if: github.event_name == 'pull_request' && steps.significant_benchmarks.outputs.changed == 'true'
        run: asv publish

      - name: Save results artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: asv-benchmark-results-${{ github.event.pull_request.head.sha || github.sha }}
          include-hidden-files: true
          path: |
            .asv/results
            .asv/html
            asv-compare-output.log
            asv-compare-changed-output.log
