#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/contributing/development/continuous_integration.html

name: conda-forge

on:
  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:  # manual trigger

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkgman: [conda, mamba]
        os: [ubuntu-latest, macos-latest]

        include:
        - os: ubuntu-latest
          platform: linux-64

        - os: macos-latest
          platform: osx-64

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }} (${{ matrix.pkgman }})
    steps:
      - name: Download lockfile
        run: wget -q https://github.com/tardis-sn/tardis/releases/latest/download/conda-${{ matrix.platform }}.lock

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            environment-file: conda-${{ matrix.platform }}.lock
            activate-environment: tardis
            use-mamba: true

      - name: Install conda-forge package
        run: ${{ matrix.pkgman }} install tardis-sn -c conda-forge
