name: docstr-coverage

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install docstr-coverage
        run: pip install docstr-coverage

      - name: Get base coverage
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          echo "BASE_COV=$(docstr-coverage -p)" >> $GITHUB_ENV

      - name: Get head coverage
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          docstr-coverage --fail-under=$BASE_COV

      - name: Blame
        if: ${{ failure() }}
        run: |
          git diff --name-only $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) | xargs docstr-coverage --accept-empty
