# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

name: mailmap

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check PR authors
        run: cat .mailmap | grep "$(git log $PR_BASE_SHA..HEAD --pretty='%aN <%aE>')"
        env:
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}

      - name: Error message
        run: |
          echo "Committer name or email couldn't be found in .mailmap"
          echo; git log $PR_BASE_SHA..HEAD --pretty='%aN <%aE>'
        if: failure()
