#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/contributing/development/continuous_integration.html

name: post-release

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch: # manual trigger

jobs:
  citation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install doi2cff
        run: pip install git+https://github.com/citation-file-format/doi2cff

      - name: Update CITATION.cff with retry
        run: |
          rm CITATION.cff
          max_attempts=5
          attempt=1
          until doi2cff init 10.5281/zenodo.592480 || [ $attempt -eq $max_attempts ]; do
            echo "Attempt $attempt failed. Retrying in $((attempt * 60)) seconds..."
            sleep $((attempt * 60))
            attempt=$((attempt + 1))
          done

      - uses: actions/upload-artifact@v5
        with:
          name: citation
          path: CITATION.cff
