name: stardis-tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}
 
env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  test-cache:
    uses: ./.github/workflows/lfs-cache.yml
    with:
      atom-data-sparse: true
      regression-data-repo: tardis-sn/tardis-regression-data
      allow_lfs_pull: ${{ github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'git-lfs-pull') }}

  build:
    needs: [test-cache]
    strategy:
      matrix:
        label: [linux-64]
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/stardis

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    if: ${{ !github.event.pull_request.draft }}
    steps:     
      - uses: actions/checkout@v6
        with:
          repository: tardis-sn/stardis

      - name: Checkout TARDIS workflow helpers
        uses: actions/checkout@v6
        with:
          path: tardis-source

      - name: Download Lock File
        run:  wget -q https://raw.githubusercontent.com/tardis-sn/stardis/main/conda-${{ matrix.label }}.lock
        shell: bash

      - name: Generate Cache Key
        run: | 
          file_hash=$(cat conda-${{ matrix.label }}.lock | shasum -a 256 | cut -d' ' -f1)
          echo "file_hash=$file_hash" >> "${GITHUB_OUTPUT}"
        id: cache-environment-key
        shell: bash
        
      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: conda-${{ matrix.label }}.lock
          cache-environment-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          cache-downloads-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          environment-name: stardis
          cache-environment: true
          cache-downloads: true
        
      - name: Install tardis
        id: install-tardis
        run: |
          pip install git+https://github.com/tardis-sn/tardis.git@${{ github.sha }}
          
      - name: Install stardis
        id: install-stardis
        run: |
          pip install -e .[test]

      - name: Setup atom data
        uses: ./tardis-source/.github/actions/setup_lfs
        with:
          atom-data-sparse: true
          regression-data-repo: tardis-sn/tardis-regression-data

      - name: Copy atom data
        run: |
          mkdir -p ~/Downloads/tardis-data
          cp ./tardis-regression-data/atom_data/kurucz_cd23_chianti_H_He_latest.h5 ~/Downloads/tardis-data/

      - name: Run stardis tests  
        run: pytest
