# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

parameters:
  - name: fetchDepth
    type: number
    default: 0

  - name: fetchRefdata
    type: boolean
    default: false

  - name: useMamba
    type: boolean
    default: false

  - name: skipInstall
    type: boolean
    default: false

steps:
  - bash: echo "##vso[task.setvariable variable=shellopts]errexit"
    displayName: 'Force BASH exit on error'
    condition: eq(variables['Agent.OS'], 'Linux')

  - bash: |
      echo "##vso[task.setvariable variable=tardis.dir]$(Build.SourcesDirectory)/tardis"
      echo "##vso[task.setvariable variable=refdata.dir]$(Build.SourcesDirectory)/tardis-refdata"
    displayName: 'Set environment variables'

  - ${{ if eq(parameters.useMamba, false) }}:
    - bash: |
        echo "##vso[task.setvariable variable=package.manager]conda"
      displayName: 'Set environment variables'

  - ${{ if eq(parameters.useMamba, true) }}:
    - bash: |
        echo "##vso[task.setvariable variable=package.manager]mamba"
      displayName: 'Set package manager'
 
  - checkout: self
    path: s/tardis
    fetchDepth: ${{ parameters.fetchDepth }}

  - ${{ if eq(parameters.fetchRefdata, true) }}:
    - checkout: git://TARDIS/tardis-refdata
      lfs: true
      displayName: 'Fetch reference data'

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'

  - bash: sudo chown -R $USER $CONDA
    displayName: 'Take ownership of conda installation'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - ${{ if eq(parameters.useMamba, true) }}:
    - bash: conda install mamba -c conda-forge -y
      displayName: 'Install Mamba'

  - ${{ if eq(parameters.skipInstall, false) }}:
    - bash: |
        cd $(tardis.dir)
        $(package.manager) env create -f tardis_env3.yml
      displayName: 'Setup environment'

  - ${{ if eq(parameters.skipInstall, false) }}:
    - bash: |
        cd $(tardis.dir)
        source activate tardis
        python setup.py install
      displayName: 'Install package'
