# Simple pipeline to test a self hosted agent.
# Set trigger and pull request trigger to none, since we do not need continuous integration.

trigger: none

pr: none
  

jobs:

- job: 'Test_Self_Hosted_Agent'
  pool:
    name: Linux


  steps:
  - bash: |
          ls
    displayName: List remote server files

  - bash: |
          python /home/youssef/helloworld.py
    displayName: Run local file